#values
gene_set0: "SLC34A1 PDILT IGF1R"
gene_set1: "CASZ1 DDX1 TMEM60 STC1 PIP5K1B"
#gene_set1: "DAB2 GAB2"
datasets: "phen meta prot"

# pathes
path_loci: "../config/locus_window.txt"
path_vcf: "/scratch/compgen/data/genetics/CHRIS13K/Imputation/WES/CHRIS13K.WES.imputed.rsq03.vep.hg38.sorted.bgzip.vcf.gz"
path_rep: "/home/dghasemisemeskandeh/projects/haploAnalysis/workflow"

# for R (03-1.R)
default:
    path_phen: "/home/dghasemisemeskandeh/projects/HaploReg/data/chris_q-norm.csv"
    path_meta: "/home/dghasemisemeskandeh/projects/HaploReg/data/chris_meta.csv"
    path_prot: "/home/dghasemisemeskandeh/projects/HaploReg/data/chris_prot.csv"
    path_comp: "/home/dghasemisemeskandeh/projects/HaploReg/data/CHRIS13K.GT.evecs"
    phenotypes: ""
