#values
gene_set: "CASZ1 DDX1 TMEM60 STC1 GAB2 SLC34A1 IGF1R PDILT SHROOM3 PIP5K1B DAB2" 
#gene_set: "PIP5K1B" #" GAB2"
datasets: "phen meta prot"

# pathes
path_loci: "../config/locus_window.txt"
path_vcf: "/scratch/compgen/data/genetics/CHRIS13K/Imputation/WES/CHRIS13K.WES.imputed.rsq03.vep.hg38.sorted.bgzip.vcf.gz"
path_rep: "/home/dghasemisemeskandeh/projects/haploAnalysis/workflow"

# for R (03-1.R)
default:
    path_phen: "/home/dghasemisemeskandeh/projects/HaploReg/data/chris_q-norm.csv"
    path_meta: "/home/dghasemisemeskandeh/projects/HaploReg/data/chris_meta.csv"
    path_prot: "/home/dghasemisemeskandeh/projects/HaploReg/data/chris_prot.csv"
    path_comp: "/home/dghasemisemeskandeh/projects/HaploReg/data/CHRIS13K.GT.evecs"
    phenotypes: ""
    datasets: "phen meta prot"
